[package]
name = "slang"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
libc = "0.2.154"
paste = "1.0.14"
slang-sys = { path = "slang-sys" }
static_assertions = "1.1.0"
thiserror = "1.0.58"

[features]
default = []
static = ["slang-sys/static"]